version: 1
disable_existing_loggers: False

formatters:
  json:
    () : pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: app.log.jsonl
    maxBytes: 10000000
    backupCount: 5

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json

loggers:
  root:
    level: INFO
    handlers:
      - file
      - console

  some_module:
    level: DEBUG
    handlers:
      - console
    propagate: no
