name: CI/CD to Docker Hub

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on any tag starting with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PASS: ${{ secrets.DB_PASS }}
      KAFKA_SERVER: ${{ secrets.KAFKA_SERVER }}
      KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC }}
      KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
      KAFKA_PASS: ${{ secrets.KAFKA_PASS }}
      KAFKA_GROUP_ID: ${{ secrets.KAFKA_GROUP_ID }}
      KAFKA_SASL_MECH: ${{ secrets.KAFKA_SASL_MECH }}
      KAFKA_OFFSET_RESET: ${{ secrets.KAFKA_OFFSET_RESET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HAMYAR_DOCKERHUB_USERNAME }}
        password: ${{ secrets.HAMYAR_DOCKERHUB_PASSWORD }}

    # - name: Extract version tag
    #   id: extract_tag
    #   run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # tags: hamyarchat/front:${{ env.TAG }}
        # tags: |
        #   hamyarchat/front:${{ env.TAG }}
        #   hamyarchat/front:latest
        tags: hamyarchat/worker:latest
        build-args: |
          DB_NAME=${{ secrets.DB_NAME }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_PASS=${{ secrets.DB_PASS }}
          KAFKA_SERVER=${{ secrets.KAFKA_SERVER }}
          KAFKA_TOPIC=${{ secrets.KAFKA_TOPIC }}
          KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME }}
          KAFKA_PASS=${{ secrets.KAFKA_PASS }}
          KAFKA_GROUP_ID=${{ secrets.KAFKA_GROUP_ID }}
          KAFKA_SASL_MECH=${{ secrets.KAFKA_SASL_MECH }}
          KAFKA_OFFSET_RESET=${{ secrets.KAFKA_OFFSET_RESET }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

    - name: Log out from Docker Hub
      run: docker logout